dataset=read.csv("C:\Users\Dell\Downloads\Python\Data science\house-price-prediction-master\kc_house_data.csv")
View(dataset)
dataset$waterfront<-factor(dataset$waterfront,labels = c("No","yes"))
library(ggplot2)
ggplot(dataset,aes(x=bedrooms,y=price))+geom_point()+geom_smooth(method=lm,se=F)
ggplot(dataset,aes(x=bathrooms,y=price))+geom_point()+geom_smooth(method=lm,se=F)
ggplot(dataset,aes(x=sqft_living,y=price))+geom_point()+geom_smooth(method=lm,se=F)
ggplot(dataset,aes(x=bedrooms))+geom_histogram(bins=30)
ggplot(dataset,aes(x=waterfront,y=price,fill=waterfront))+geom_boxplot()
ggplot(dataset,aes(x=view,y=price,fill=view))+geom_point()+geom_smooth(method=lm,se=F)
ggplot(dataset,aes(x=grades,y=price))+geom_point()+geom_smooth(method=lm,se=F)
ggplot(dataset,aes(x=yr_renovated-yr_built,y=price))+geom_point()+geom_smooth(method=lm,se=F)
